config/routes.rb
Rails.application.routes.draw do
  resources :cities
  root to: 'cities#index'
  get '/admin', to: 'cities#admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.api_call(key)
    uri=URI(URI::encode("http://api.openweathermap.org/data/2.5/weather?#{key}"+
                "&APPID=#{Rails.application.secrets.openweathermap_appid}&units=metric&lang=RU"))
    res=Rails.cache.fetch(key, expires_in: 10.minutes) do
      begin
      Net::HTTP.get_response(uri)
      rescue SocketError => details
        logger.info(details)
      end
    end
    case res
      when Net::HTTPSuccess
        JSON.parse(res.body)
      else
        Rails.cache.delete(key)
        return false
    end
  end
end

app/models/city.rb
class City < ApplicationRecord
  validates :lat , numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 , :allow_nil => true}
  validates :lng, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 , :allow_nil => true}
  validate :validate_for_cooords
  validate :validate_if_usefull_for_api
  validates_numericality_of :city_id, :allow_nil => true
  after_create :search_name_for_city

  KEYS=[['name', 'q'],['zip_code','zip'],['lat','coords'],['lng','coords'],['city_id','id']]
  def weather_info
    info=ApplicationRecord.api_call(key_for_api)
    return :error_from_api if !info || !(info.include?('cod') and info['cod']==200)
    Weather.new(info)
  end

  def weather_descriptions
    return ApplicationRecord.api_call(key_for_api)['weather'].map {|desc| desc['description']}
  end

  def lat_from_api
    ApplicationRecord.api_call(key_for_api)['coord']['lat']
  end
  def lng_from_api
    ApplicationRecord.api_call(key_for_api)['coord']['lon']
  end

  def coords
    "lat=#{lat}&lon=#{lng}"
  end

  def key_for_api
    key=KEYS.detect{|k| k[0]==use_for_api}
    key[1]=='coords' ? coords : "#{key[1]}=#{attributes.detect{|a| a[0]==key[0]}[1]}"
  end


  private

  def validate_for_cooords
    if (lat.blank? or lng.blank?) and !(lat.blank? and lng.blank?)
      errors.add(:coords, "Укажите оба поля коордианат или не указывайте их вообще")
    end
  end

  def validate_if_usefull_for_api
    if !errors.any? and ApplicationRecord.api_call(key_for_api)['cod']=='404'
      errors.add(:name, "Не найдена информация о погоде в городе по таким параметрам")
    end
  end

  def search_name_for_city
    update(name:ApplicationRecord.api_call(key_for_api)['name'])
  end
end

app/models/weather.rb
class Weather < ApplicationRecord
  attr_accessor :temp, :pressure, :humidity, :temp_min, :temp_max, :visibility, :wind_speed, :wind_deg, :clouds
  WIND_DIRECTIONS=[['N', 0, 11.25], ['NNE', 11.25, 33.75], ['NE', 33.75, 56.25],
                   ['ENE', 56.25, 78.75], ['E', 78.75, 101.25], ['ESE', 101.25, 123.75],
                   ['SE', 123.75, 146.25], ['SSE', 146.25, 168.75], ['S', 168.75, 191.25],
                   ['SSW', 191.25, 213.75], ['SW', 213.75, 236.25], ['WSW', 236.25, 258.75],
                   ['W', 258.75, 281.25], ['WNW', 281.25, 303.75], ['NW', 303.75, 326.25],
                   ['NNW', 326.25, 348.75], ['N', 348.75, 360]]

  def initialize(options={})
    super(options['main'])
    @visibility=options['visibility']
    if options['wind']
      @wind_speed=options['wind']['speed']
      @wind_deg=options['wind']['deg']
    end
    if options['clouds']
      @clouds=options['clouds']['all']
    end
  end

  def wind_direction
    WIND_DIRECTIONS.detect { |dir| wind_deg.between? dir[1], dir[2] }[0] if wind_deg
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: Rails.application.secrets.username, password: Rails.application.secrets.password, only: [:edit, :update, :admin, :destroy, :create]
  skip_before_action :verify_authenticity_token, if: :js_request?

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  def admin
    @cities = City.all
    @admin=true
    respond_to do |format|
      format.html { render :index }
    end
  end


  # GET /cities/1
  # GET /cities/1.json
  def show
    @weather=@city.weather_info
    unless @weather==:error_from_api
      @weather_description=@city.weather_descriptions.join(', ')
    else
      flash[:alert]='Нам не удалось получить данные от API. Попробуйте позже.'
    end
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    @city.use_for_api=@city.attributes.slice('name', 'city_id', 'lat', 'lng', 'zip_code').to_a.detect { |a| !a[1].blank? }[0]

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:name, :zip_code, :lat, :lng, :city_id)
  end

  def js_request?
    request.format.js?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Имя' %>
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <%= f.label 'Индекс' %>
      <%= f.text_field :zip_code %>
    </div>

    <div class="field">
      <%= f.label 'ID города' %>
      <%= f.text_field :city_id %>
    </div>

    <div class="field">
      <%= f.label 'Координаты (Latitude, Longitude)' %>
      <%= f.text_field :lat %>, <%= f.text_field :lng %>
    </div>

  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Редактирование названия города</h1>

<%= render 'form', city: @city %>

<%= link_to 'Показать', @city %> |
<%= link_to 'Назад', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Прогноз погоды</h1>

<table>
  <thead>
    <tr>
      <th>Город</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to 'Узнать погоду', city %></td>
        <td><%= link_to 'Редактировать', edit_city_path(city) if @admin%></td>
        <td><%= link_to 'Удалить', city, method: :delete, data: { confirm: 'Are you sure?' }  if @admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый город', new_city_path if @admin%>

app/views/cities/new.html.erb
<h1>Новый город</h1>

<%= render 'form', city: @city %>

<%= link_to 'Назад', cities_path %>

app/views/cities/show.html.erb
<%= content_for(:body_attributes) do %>data-no-turbolink<% end %>
<p id="notice"><%= notice %></p>


<h1>
  <%= @city.name %>
</h1>
<% if alert %>
    <p id="alert"><%= alert %></p>
    <%else%>
<p>
  <strong>Погода:</strong>
  <%= @weather_description %>
</p>

<p>
  <strong>Температура:</strong>
  <%= "#{@weather.temp}C (от #{@weather.temp_min}C до #{@weather.temp_max}C)" %>
</p>

<p>
  <strong>Ветер:</strong>
  <%= "#{@weather.wind_speed} м/с, #{@weather.wind_direction}" %>
</p>
<p>
  <strong>Видимость:</strong>
  <%= "#{@weather.visibility} м" %>
</p>
    <% if Rails.application.secrets.google_appid %>
<script src="//maps.google.com/maps/api/js?v=3&key=<%=Rails.application.secrets.google_appid%>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div style='width: 400px;height: 400px;'>
  <div id="map" style='width: 400px; height: 400px;'></div>
</div>
<script src="<%= city_path(@city, format: :js) %>"></script>
<% end %>
<%end%>
<%= link_to 'Назад', cities_path %>

app/views/cities/show.js.erb
handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      lat: <%=@city.lat_from_api%>,
      lng: <%=@city.lng_from_api%>,
      picture: {
        url: "http://www.google.com/intl/en_ALL/mapfiles/marker.png",
        width:  36,
        height: 36
      }
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(10);
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForecast</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body <%= yield(:body_attributes) %>>
    <%= yield %>
  </body>
</html>